'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Books',
      [
        {
          title: 'Book 1',
          description: 'Description of Book 1',
          pages: 100,
          price: 10.99,
          publishedAt: new Date(),
          image: 'https://example.com/book1.jpg',
          blob: Buffer.from('Book 1 content'),
          reference_id: 1,
          hierarchy_reference_id: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 2',
          description: 'Description of Book 2',
          pages: 200,
          price: 20.99,
          publishedAt: new Date(),
          image: 'https://example.com/book2.jpg',
          blob: Buffer.from('Book 2 content'),
          reference_id: 2,
          hierarchy_reference_id: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 3',
          description: 'Description of Book 3',
          pages: 300,
          price: 30.99,
          publishedAt: new Date(),
          image: 'https://example.com/book3.jpg',
          blob: Buffer.from('Book 3 content'),
          reference_id: 3,
          hierarchy_reference_id: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 4',
          description: 'Description of Book 4',
          pages: 100,
          price: 10.99,
          publishedAt: new Date(),
          image: 'https://example.com/book4.jpg',
          blob: Buffer.from('Book 4 content'),
          reference_id: 4,
          hierarchy_reference_id: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 5',
          description: 'Description of Book 5',
          pages: 200,
          price: 20.99,
          publishedAt: new Date(),
          image: 'https://example.com/book5.jpg',
          blob: Buffer.from('Book 5 content'),
          reference_id: 5,
          hierarchy_reference_id: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 6',
          description: 'Description of Book 6',
          pages: 300,
          price: 30.99,
          publishedAt: new Date(),
          image: 'https://example.com/book6.jpg',
          blob: Buffer.from('Book 6 content'),
          reference_id: 6,
          hierarchy_reference_id: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 7',
          description: 'Description of Book 7',
          pages: 300,
          price: 30.99,
          publishedAt: new Date(),
          image: 'https://example.com/book7.jpg',
          blob: Buffer.from('Book 7 content'),
          reference_id: 7,
          hierarchy_reference_id: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 8',
          description: 'Description of Book 8',
          pages: 300,
          price: 30.99,
          publishedAt: new Date(),
          image: 'https://example.com/book8.jpg',
          blob: Buffer.from('Book 8 content'),
          reference_id: 8,
          hierarchy_reference_id: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 9',
          description: 'Description of Book 9',
          pages: 300,
          price: 30.99,
          publishedAt: new Date(),
          image: 'https://example.com/book9.jpg',
          blob: Buffer.from('Book 9 content'),
          reference_id: 9,
          hierarchy_reference_id: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: 'Book 10',
          description: 'Description of Book 10',
          pages: 300,
          price: 30.99,
          publishedAt: new Date(),
          image: 'https://example.com/book10.jpg',
          blob: Buffer.from('Book 10 content'),
          reference_id: 10,
          hierarchy_reference_id: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Books', null, {});
  },
};
